version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: vsce
    versions:
    - 1.84.0
    - 1.85.0
    - 1.85.1
    - 1.86.0
    - 1.87.0
  - dependency-name: lodash
    versions:
    - 4.17.20
