parameters:
  dependsOn: ''
  versionSpec: '10.x'

jobs:
- job: 'Deploy'
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: ${{ parameters.versionSpec }}
      displayName: 'Install Node.js'
    - script: yarn
      displayName: 'Install Dependencies'
    - bash: |
        set -e

        npm run build

        if [[ "$TARGET" = "stable" ]]; then
          REPO=$(git config remote.origin.url)
          TARGET_BRANCH="stable"
          git clone $REPO dist -b $TARGET_BRANCH
          NEW_PACKAGE_VERSION=$(node -p "require('./package.json').version")
          OLD_PACKAGE_VERSION=$(node -p "require('./dist/package.json').version")
          echo -e "stable pr - checking semvar without publishing."
          node ./scripts/versionCompare.js $NEW_PACKAGE_VERSION $OLD_PACKAGE_VERSION
          exit 0
        fi

        if [[ "$BRANCH" != "stable" ]]; then
          echo -e "Not publishing for a non stable branch push."
          exit 0
        fi

        echo -e "Publishing for a stable branch push."

        npx vsce publish -p "${PUBLISH_TOKEN}"
      env:
        TARGET: $(System.PullRequest.TargetBranch)
        BRANCH: $(Build.SourceBranchName)
        PUBLISH_TOKEN: $(publishToken)
      displayName: 'Deploy'
